### ISSUE TITLE
(debian/ubuntu repository) cannot import signing key

### ISSUE THREAD

**Issue by jclain** [signal18/replication-manager#297]
hello,

I'm following the instructions from https://docs.signal18.io/installation/setup-instructions

When installing replication-manager from the debian/ubuntu repository, the key import fails:
```
$ sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com FAE20E50
Executing: /tmp/apt-key-gpghome.mgTbpYFWHT/gpg.1.sh --recv-keys --keyserver keyserver.ubuntu.com FAE20E50
gpg: keyserver receive failed: Server indicated a failure
```

when going to the web interface of the keyserver, it says the key does not (no longer?) exists
can you either repost the key to the keyserver or allow us to download it from elsewhere?

thanks in advance. best regards,
Jephté Clain

**Comment by tanji** [comment]
Hello, thanks for reporting - not sure why the key disappeared. However it should work now, alternatively please use `keys.gnupg.net` - it could be that the ubuntu keyserver is experiencing issues.

Regards

**Comment by jclain** [comment]
hello. thank you very much for your quick response. however, it still doesn't work (the error is the same) from either keyserver.ubuntu.com nor keys.gnupg.net
and, from the web interface (I show here the output of wget, but I did go directly to the web interface with a web browser)
```
$ wget -qSO - 'http://keyserver.ubuntu.com/pks/lookup?search=FAE20E50&fingerprint=on&op=index'
  HTTP/1.1 404 Not Found
  ...
$ wget -qSO - 'http://keys.gnupg.net/pks/lookup?search=FAE20E50&fingerprint=on&op=index'
  HTTP/1.1 404 Not found
  ...
```
I'll retry tomorrow as it just could be a "replication" delay?
but it is the same behavior that I have got since a month ago

EDIT: the key was not found because I did not put "0x" in front of it. duh!
```
$ wget -qO - 'http://keyserver.ubuntu.com/pks/lookup?search=0xFAE20E50&fingerprint=on&op=index'
.... content with details of the key ...
```

**Comment by jclain** [comment]
I tried from a ubuntu VM (my servers are on debian) and it worked
So there must be a client filtering of some sort, perhaps based on user-agent...
sorry for the bother.

If a find a way to download the key from debian, I'll update this issue

maybe you could host the key somewhere on your servers (your CI server for example?). it could solve that particular problem

have a nice day. regards,

**Comment by jclain** [comment]
well, if I force the usage of the port 80, it works from debian
```
$ sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 FAE20E50
Executing: /tmp/apt-key-gpghome.OGrXsfadFe/gpg.1.sh --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 FAE20E50
gpg: clef 28A486AAFAE20E50 : clef publique « Signal 18 IT Team (signing key) <info@signal18.io> » importée
gpg:       Quantité totale traitée : 1
gpg:                     importées : 1
```

So there is something preventing me from accessing the server on standard hkp port 11371 from debian (but there is no problem from ubuntu... weird...)

EDIT: you can also manually download the key from the web interface http://keyserver.ubuntu.com by searching it with the prefix "0x" e.g `0xFAE20E50`

hope this help someone having the same issue as mine. best regards,
Jephté Clain

**Comment by tanji** [comment]
Thanks for the feedback!
