### ISSUE TITLE
V2.3.15 service cannot start. when no cluster is discovered in configs

### ISSUE THREAD

**Issue by tanglu86** [signal18/replication-manager#538]
I tried to upgrade RM to V2.3.15, but after starting the service, I found that ports 10001 and 10005 were not listening properly. 

There is no useful information for reference in the replication-manager.log, and a "runtime error: invalid memory address or nil pointer dereference" appeared in /var/log/messages. 

How should I fix this problem?

Here is a configuration example:

### /etc/replication-manager/config.toml
```
[Default]
include = "/etc/replication-manager/cluster.d"
monitoring-save-config = false
monitoring-datadir = "/var/lib/replication-manager"
#monitoring-sharedir = "/usr/share/replication-manager"
monitoring-ticker = 5
monitoring-performance-schema = false
monitoring-processlist = false
monitoring-queries = false

log-file = "/var/log/replication-manager.log"
log-heartbeat = false
#log-syslog = false

http-server = true
http-bind-address = "0.0.0.0"
http-port = "10001"
http-auth = false
http-session-lifetime =   3600

api-credentials = "admin:repman"
api-port = "10005"
#api-credentials-acl-allow =  "admin:cluster proxy db prov,dba:cluster proxy db,foo:"
#api-credentials-acl-discard = false
#api-credentials-external = "dba:repman,foo:bar"

#prov-orchestrator = "onpremise"
#monitoring-address = "127.0.0.1"
#http-refresh-interval = 4000
#api-credentials-acl-allow = "admin:cluster db prov"
```

### /etc/replication-manager/cluster.d/test.toml
```
[Default]
title = "ClusterTest"
db-servers-hosts = "127.0.0.1:5055,127.0.0.1:5056"
db-servers-credential = "skysql:skyvodka"
replication-credential = "skysql:skyvodka"
failover-mode = "manual"
```

### Start the service.
```
systemctl start replication-manager
```

### When I start the service using the default configuration file, it still doesn't work properly.
```
[Default]
include = "/etc/replication-manager/cluster.d"
prov-orchestrator = "onpremise"
monitoring-ticker = 2

log-file = "/var/log/replication-manager.log"
log-heartbeat = false

http-server = true
http-bind-address = "0.0.0.0"
http-port = "10001"
http-auth = false
http-session-lifetime =   3600
http-refresh-interval = 4000

api-credentials = "admin:repman"
api-credentials-acl-allow = "admin:cluster db prov"
api-port = "10005"

```

### log
```
Feb 21 10:27:17 eth0 systemd: Started replication-manager open source.
Feb 21 10:27:17 eth0 replication-manager-osc: time="2024-02-21T10:27:17+08:00" level=info msg="Reading default section include directory: /etc/replication-manager/cluster.d"
Feb 21 10:27:17 eth0 replication-manager-osc: time="2024-02-21T10:27:17+08:00" level=warning msg="No monitoring-save-config variable in default section config change lost on restart"
Feb 21 10:27:17 eth0 replication-manager-osc: time="2024-02-21T10:27:17+08:00" level=info msg="Log to file: /var/log/replication-manager.log" version=v2.3.15
Feb 21 10:27:17 eth0 replication-manager-osc: time="2024-02-21T10:27:17+08:00" level=info msg="Replication-Manager started in daemon mode" version=v2.3.15
Feb 21 10:27:17 eth0 replication-manager-osc: time="2024-02-21T10:27:17+08:00" level=info msg="repman.Conf.WorkingDir : /var/lib/replication-manager"
Feb 21 10:27:17 eth0 replication-manager-osc: time="2024-02-21T10:27:17+08:00" level=info msg="repman.Conf.ShareDir : /usr/share/replication-manager"
Feb 21 10:27:17 eth0 replication-manager-osc: panic: runtime error: invalid memory address or nil pointer dereference
Feb 21 10:27:17 eth0 replication-manager-osc: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e10ad5]
Feb 21 10:27:17 eth0 replication-manager-osc: goroutine 1 [running]:
Feb 21 10:27:17 eth0 replication-manager-osc: github.com/signal18/replication-manager/server.(*ReplicationManager).StartCluster(0xc000146000, {0x23215f2, 0x7})
Feb 21 10:27:17 eth0 replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server.go:1105 +0x295
Feb 21 10:27:17 eth0 replication-manager-osc: github.com/signal18/replication-manager/server.(*ReplicationManager).Run(0xc000146000)
Feb 21 10:27:17 eth0 replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server.go:893 +0x23c8
Feb 21 10:27:17 eth0 replication-manager-osc: github.com/signal18/replication-manager/server.glob..func6(0x3fcb880, {0x231cfc4, 0x0, 0x0})
Feb 21 10:27:17 eth0 replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server_monitor.go:745 +0x111
Feb 21 10:27:17 eth0 replication-manager-osc: github.com/spf13/cobra.(*Command).execute(0x3fcb880, {0x4024118, 0x0, 0x0})
Feb 21 10:27:17 eth0 replication-manager-osc: /var/jenkins_home/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x5f8
Feb 21 10:27:17 eth0 replication-manager-osc: github.com/spf13/cobra.(*Command).ExecuteC(0x3fcb0a0)
Feb 21 10:27:17 eth0 replication-manager-osc: /var/jenkins_home/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x38d
Feb 21 10:27:17 eth0 replication-manager-osc: github.com/spf13/cobra.(*Command).Execute(...)
Feb 21 10:27:17 eth0 replication-manager-osc: /var/jenkins_home/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
Feb 21 10:27:17 eth0 replication-manager-osc: github.com/signal18/replication-manager/server.Execute()
Feb 21 10:27:17 eth0 replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server_cmd.go:104 +0x25
Feb 21 10:27:17 eth0 replication-manager-osc: main.main()
Feb 21 10:27:17 eth0 replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/main_server.go:24 +0x19
Feb 21 10:27:17 eth0 systemd: replication-manager.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 21 10:27:17 eth0 systemd: Unit replication-manager.service entered failed state.
Feb 21 10:27:17 eth0 systemd: replication-manager.service failed.
Feb 21 10:27:17 eth0 systemd: replication-manager.service holdoff time over, scheduling restart.
Feb 21 10:27:17 eth0 systemd: Stopped replication-manager open source.

```

**Comment by svaroqui** [comment]
I'll get look today  thank for repoting

**Comment by svaroqui** [comment]
Ok i found the issue , in etc/replication-manager/cluster.d/test.toml you need to replace [Default] by [test]

I have fixed the issue that without any cluster defined it still start a default cluster

Is this an issue on your side or do you think we deliver this as default setup in packaging that would be bad ?

**Comment by tanglu86** [comment]
> Ok i found the issue , in etc/replication-manager/cluster.d/test.toml you need to replace [Default] by [test]
> 
> I have fixed the issue that without any cluster defined it still start a default cluster
> 
> Is this an issue on your side or do you think we deliver this as default setup in packaging that would be bad ?


First of all, thank you for your answer. I have updated the configuration file, but the problem still exists. The updated configuration is as follows:

### config.toml
```
[Default]
include = "/etc/replication-manager/cluster.d"
monitoring-save-config = false
monitoring-datadir = "/var/lib/replication-manager"
monitoring-ticker = 5
monitoring-performance-schema = false
monitoring-processlist = false
monitoring-queries = false
log-file = "/var/log/replication-manager.log"
log-heartbeat = false
http-server = true
http-bind-address = "0.0.0.0"
http-port = "10001"
http-auth = false
http-session-lifetime =   3600
api-credentials = "admin:repman"
api-port = "10005"
```

### cluster.d/test.toml
```
[test]
title = "test"
db-servers-hosts = "172.22.8.13:3333,172.22.8.14:3333"
db-servers-prefered-master = "172.22.8.13:3333"
db-servers-credential = "123456"
db-servers-connect-timeout = 10
replication-credential = "repl:123456"
verbose = false 
log-failed-election  = true
log-level = 1
log-rotate-max-age = 7
log-rotate-max-backup = 7
log-rotate-max-size = 5
log-sql-in-monitoring   = true
log-sst = true

failover-mode = "manual"
failover-readonly-state = true
failover-max-slave-delay = 0
failover-event-scheduler = false
failover-event-status = false
failover-falsepositive-ping-counter = 10
failover-falsepositive-heartbeat = true
failover-limit = 0
failover-time-limit = 3600
failover-at-sync = true
failover-restart-unsafe = false

switchover-wait-kill = 10000
switchover-wait-trx = 10
switchover-wait-write-query = 10
switchover-at-equal-gtid = false
switchover-at-sync = true
switchover-max-slave-delay = 30

check-replication-filters = true
check-binlog-filters = true
check-replication-state = true

force-slave-heartbeat= false
force-slave-heartbeat-retry = 5
force-slave-heartbeat-time = 3
force-slave-gtid-mode = false
force-slave-semisync = false
force-slave-failover-readonly-state = false
force-binlog-row = false
force-binlog-annotate = false
force-binlog-slowqueries = false
force-binlog-compress = false
force-binlog-checksum = false
force-inmemory-binlog-cache-size = false
force-disk-relaylog-size-limit = false
force-disk-relaylog-size-limit-size = 1000000000
force-sync-binlog = false
force-sync-innodb = false
```

###  /var/log/messages
```
Feb 22 09:28:09 [localhost] systemd: Started replication-manager open source.
Feb 22 09:28:09 [localhost] systemd: Removed slice User Slice of root.
Feb 22 09:28:09 [localhost] replication-manager-osc: time="2024-02-22T09:28:09+08:00" level=info msg="Reading default section include directory: /etc/replication-manager/cluster.d"
Feb 22 09:28:09 [localhost] replication-manager-osc: time="2024-02-22T09:28:09+08:00" level=warning msg="No monitoring-save-config variable in default section config change lost on restart"
Feb 22 09:28:09 [localhost] replication-manager-osc: time="2024-02-22T09:28:09+08:00" level=info msg="Log to file: /var/log/replication-manager.log" version=v2.3.15
Feb 22 09:28:09 [localhost] replication-manager-osc: time="2024-02-22T09:28:09+08:00" level=info msg="Replication-Manager started in daemon mode" version=v2.3.15
Feb 22 09:28:09 [localhost] replication-manager-osc: time="2024-02-22T09:28:09+08:00" level=info msg="repman.Conf.WorkingDir : /var/lib/replication-manager"
Feb 22 09:28:09 [localhost] replication-manager-osc: time="2024-02-22T09:28:09+08:00" level=info msg="repman.Conf.ShareDir : /usr/share/replication-manager"
Feb 22 09:28:09 [localhost] replication-manager-osc: panic: runtime error: invalid memory address or nil pointer dereference
Feb 22 09:28:09 [localhost] replication-manager-osc: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e10ad5]
Feb 22 09:28:09 [localhost] replication-manager-osc: goroutine 1 [running]:
Feb 22 09:28:09 [localhost] replication-manager-osc: github.com/signal18/replication-manager/server.(*ReplicationManager).StartCluster(0xc0002c6000, {0x23215f2, 0x7})
Feb 22 09:28:09 [localhost] replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server.go:1105 +0x295
Feb 22 09:28:09 [localhost] replication-manager-osc: github.com/signal18/replication-manager/server.(*ReplicationManager).Run(0xc0002c6000)
Feb 22 09:28:09 [localhost] replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server.go:893 +0x23c8
Feb 22 09:28:09 [localhost] replication-manager-osc: github.com/signal18/replication-manager/server.glob..func6(0x3fcb880, {0x231cfc4, 0x0, 0x0})
Feb 22 09:28:09 [localhost] systemd: replication-manager.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 22 09:28:09 [localhost] replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server_monitor.go:745 +0x111
Feb 22 09:28:09 [localhost] replication-manager-osc: github.com/spf13/cobra.(*Command).execute(0x3fcb880, {0x4024118, 0x0, 0x0})
Feb 22 09:28:09 [localhost] replication-manager-osc: /var/jenkins_home/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x5f8
Feb 22 09:28:09 [localhost] replication-manager-osc: github.com/spf13/cobra.(*Command).ExecuteC(0x3fcb0a0)
Feb 22 09:28:09 [localhost] replication-manager-osc: /var/jenkins_home/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x38d
Feb 22 09:28:09 [localhost] replication-manager-osc: github.com/spf13/cobra.(*Command).Execute(...)
Feb 22 09:28:09 [localhost] replication-manager-osc: /var/jenkins_home/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
Feb 22 09:28:09 [localhost] replication-manager-osc: github.com/signal18/replication-manager/server.Execute()
Feb 22 09:28:09 [localhost] replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/server_cmd.go:104 +0x25
Feb 22 09:28:09 [localhost] replication-manager-osc: main.main()
Feb 22 09:28:09 [localhost] replication-manager-osc: /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/main_server.go:24 +0x19
Feb 22 09:28:09 [localhost] systemd: Unit replication-manager.service entered failed state.
Feb 22 09:28:09 [localhost] systemd: replication-manager.service failed.
Feb 22 09:28:10 [localhost] systemd: replication-manager.service holdoff time over, scheduling restart.
Feb 22 09:28:10 [localhost] systemd: Stopped replication-manager open source.
Feb 22 09:28:10 [localhost] systemd: Started replication-manager open source.

```

**Comment by tanglu86** [comment]
I tried using the default cluster.toml and it seems to work normally now, so it must have been a problem with my configuration.

**Comment by svaroqui** [comment]
Yes ok it will be fixed in next release , so that when no cluster is discover the a Default cluster is loaded  with empty server list
